package Interfaces;

import java.awt.Color;
/**
 *
 * @author Luis Bizarro
 */

//Para el reloj
import java.util.*;

public class MenuAdministrador extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form Plantilla
     */
    
    int xMouse, yMouse;
    
    //Para el reloj
    String hora,minutos,segundos, ampm;
    Calendar calendario;
    Thread h1;
    
    public MenuAdministrador() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        // Iniciar el hilo para el reloj
        h1 = new Thread(this);
        h1.start();

        // Mostrar el nombre de usuario (simulado en este caso)
        AdminInSesion_1 ventanaAdminSesion = new AdminInSesion_1();
        labelNombreMostrar.setText(ventanaAdminSesion.nombreDeUsuario + "!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        labelPark = new javax.swing.JLabel();
        labelSmart = new javax.swing.JLabel();
        panelBotonExit = new javax.swing.JPanel();
        labelExit = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        panelRound2 = new Interfaces.PanelRound();
        panelVerEstacionamiento = new Interfaces.PanelRound();
        labelVerEstacionamiento = new javax.swing.JLabel();
        panelModificarDisponibilidad = new Interfaces.PanelRound();
        labelModificarDisponibilidad = new javax.swing.JLabel();
        panelModificarTareas = new Interfaces.PanelRound();
        labelModificarTareas = new javax.swing.JLabel();
        panelGestionEspacios = new Interfaces.PanelRound();
        labelRegistrarPago = new javax.swing.JLabel();
        panelRegistrarNuevoUsuario = new Interfaces.PanelRound();
        labelRegistrarNuevoUsuario = new javax.swing.JLabel();
        panelRegistroDePagos = new Interfaces.PanelRound();
        labelRegistroDePagos = new javax.swing.JLabel();
        panelModificarDatosUsuario = new Interfaces.PanelRound();
        labelModificarDatosUsuario = new javax.swing.JLabel();
        labelBienvenidos = new javax.swing.JLabel();
        imagenPuntosSuspensivos = new javax.swing.JLabel();
        labelNombreMostrar = new javax.swing.JLabel();
        labelReloj = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        labelPark.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        labelPark.setForeground(new java.awt.Color(255, 255, 255));
        labelPark.setText("Park");

        labelSmart.setBackground(new java.awt.Color(41, 239, 130));
        labelSmart.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        labelSmart.setForeground(new java.awt.Color(41, 239, 130));
        labelSmart.setText("Smart");

        panelBotonExit.setBackground(new java.awt.Color(204, 204, 204));
        panelBotonExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelBotonExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelBotonExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelBotonExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelBotonExitMouseExited(evt);
            }
        });

        labelExit.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelExit.setText("X");

        javax.swing.GroupLayout panelBotonExitLayout = new javax.swing.GroupLayout(panelBotonExit);
        panelBotonExit.setLayout(panelBotonExitLayout);
        panelBotonExitLayout.setHorizontalGroup(
            panelBotonExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelExit, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );
        panelBotonExitLayout.setVerticalGroup(
            panelBotonExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPark)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSmart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 804, Short.MAX_VALUE)
                .addComponent(panelBotonExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBotonExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(84, 84, 84))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelSmart, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(labelPark, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 50));

        jPanel3.setBackground(new java.awt.Color(243, 243, 243));

        panelRound2.setBackground(new java.awt.Color(255, 255, 255));
        panelRound2.setRoundBottomLeft(50);
        panelRound2.setRoundBottomRight(50);
        panelRound2.setRoundTopLeft(50);
        panelRound2.setRoundTopRight(50);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelVerEstacionamiento.setBackground(new java.awt.Color(0, 0, 0));
        panelVerEstacionamiento.setRoundBottomLeft(25);
        panelVerEstacionamiento.setRoundBottomRight(25);
        panelVerEstacionamiento.setRoundTopLeft(25);
        panelVerEstacionamiento.setRoundTopRight(25);

        labelVerEstacionamiento.setFont(new java.awt.Font("Roboto Black", 0, 28)); // NOI18N
        labelVerEstacionamiento.setForeground(new java.awt.Color(255, 255, 255));
        labelVerEstacionamiento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelVerEstacionamiento.setText("VER ESTACIONAMIENTO");
        labelVerEstacionamiento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelVerEstacionamiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelVerEstacionamientoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelVerEstacionamientoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelVerEstacionamientoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelVerEstacionamientoLayout = new javax.swing.GroupLayout(panelVerEstacionamiento);
        panelVerEstacionamiento.setLayout(panelVerEstacionamientoLayout);
        panelVerEstacionamientoLayout.setHorizontalGroup(
            panelVerEstacionamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVerEstacionamientoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelVerEstacionamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelVerEstacionamientoLayout.setVerticalGroup(
            panelVerEstacionamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelVerEstacionamiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
        );

        panelRound2.add(panelVerEstacionamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 27, -1, -1));

        panelModificarDisponibilidad.setBackground(new java.awt.Color(0, 0, 0));
        panelModificarDisponibilidad.setRoundBottomLeft(25);
        panelModificarDisponibilidad.setRoundBottomRight(25);
        panelModificarDisponibilidad.setRoundTopLeft(25);
        panelModificarDisponibilidad.setRoundTopRight(25);

        labelModificarDisponibilidad.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        labelModificarDisponibilidad.setForeground(new java.awt.Color(255, 255, 255));
        labelModificarDisponibilidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelModificarDisponibilidad.setText("MODIFICAR DISPONIBILIDAD");
        labelModificarDisponibilidad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelModificarDisponibilidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelModificarDisponibilidadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelModificarDisponibilidadMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelModificarDisponibilidadLayout = new javax.swing.GroupLayout(panelModificarDisponibilidad);
        panelModificarDisponibilidad.setLayout(panelModificarDisponibilidadLayout);
        panelModificarDisponibilidadLayout.setHorizontalGroup(
            panelModificarDisponibilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelModificarDisponibilidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelModificarDisponibilidadLayout.setVerticalGroup(
            panelModificarDisponibilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelModificarDisponibilidad, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );

        panelRound2.add(panelModificarDisponibilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 288, -1));

        panelModificarTareas.setBackground(new java.awt.Color(0, 0, 0));
        panelModificarTareas.setRoundBottomLeft(25);
        panelModificarTareas.setRoundBottomRight(25);
        panelModificarTareas.setRoundTopLeft(25);
        panelModificarTareas.setRoundTopRight(25);

        labelModificarTareas.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        labelModificarTareas.setForeground(new java.awt.Color(255, 255, 255));
        labelModificarTareas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelModificarTareas.setText("MODIFICAR TARIFAS");
        labelModificarTareas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelModificarTareas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelModificarTareasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelModificarTareasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelModificarTareasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelModificarTareasLayout = new javax.swing.GroupLayout(panelModificarTareas);
        panelModificarTareas.setLayout(panelModificarTareasLayout);
        panelModificarTareasLayout.setHorizontalGroup(
            panelModificarTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelModificarTareas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
        );
        panelModificarTareasLayout.setVerticalGroup(
            panelModificarTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelModificarTareas, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );

        panelRound2.add(panelModificarTareas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        panelGestionEspacios.setBackground(new java.awt.Color(0, 0, 0));
        panelGestionEspacios.setRoundBottomLeft(25);
        panelGestionEspacios.setRoundBottomRight(25);
        panelGestionEspacios.setRoundTopLeft(25);
        panelGestionEspacios.setRoundTopRight(25);

        labelRegistrarPago.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        labelRegistrarPago.setForeground(new java.awt.Color(255, 255, 255));
        labelRegistrarPago.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRegistrarPago.setText("REGISTRAR PAGO");
        labelRegistrarPago.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelRegistrarPago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRegistrarPagoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelRegistrarPagoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelRegistrarPagoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelGestionEspaciosLayout = new javax.swing.GroupLayout(panelGestionEspacios);
        panelGestionEspacios.setLayout(panelGestionEspaciosLayout);
        panelGestionEspaciosLayout.setHorizontalGroup(
            panelGestionEspaciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelRegistrarPago, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
        );
        panelGestionEspaciosLayout.setVerticalGroup(
            panelGestionEspaciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelRegistrarPago, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );

        panelRound2.add(panelGestionEspacios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        panelRegistrarNuevoUsuario.setBackground(new java.awt.Color(0, 0, 0));
        panelRegistrarNuevoUsuario.setRoundBottomLeft(25);
        panelRegistrarNuevoUsuario.setRoundBottomRight(25);
        panelRegistrarNuevoUsuario.setRoundTopLeft(25);
        panelRegistrarNuevoUsuario.setRoundTopRight(25);

        labelRegistrarNuevoUsuario.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        labelRegistrarNuevoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        labelRegistrarNuevoUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRegistrarNuevoUsuario.setText("REGISTRAR NUEVO USUARIO");
        labelRegistrarNuevoUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelRegistrarNuevoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRegistrarNuevoUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelRegistrarNuevoUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelRegistrarNuevoUsuarioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelRegistrarNuevoUsuarioLayout = new javax.swing.GroupLayout(panelRegistrarNuevoUsuario);
        panelRegistrarNuevoUsuario.setLayout(panelRegistrarNuevoUsuarioLayout);
        panelRegistrarNuevoUsuarioLayout.setHorizontalGroup(
            panelRegistrarNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelRegistrarNuevoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
        );
        panelRegistrarNuevoUsuarioLayout.setVerticalGroup(
            panelRegistrarNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrarNuevoUsuarioLayout.createSequentialGroup()
                .addComponent(labelRegistrarNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelRound2.add(panelRegistrarNuevoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        panelRegistroDePagos.setBackground(new java.awt.Color(0, 0, 0));
        panelRegistroDePagos.setRoundBottomLeft(25);
        panelRegistroDePagos.setRoundBottomRight(25);
        panelRegistroDePagos.setRoundTopLeft(25);
        panelRegistroDePagos.setRoundTopRight(25);

        labelRegistroDePagos.setFont(new java.awt.Font("Roboto Black", 0, 22)); // NOI18N
        labelRegistroDePagos.setForeground(new java.awt.Color(255, 255, 255));
        labelRegistroDePagos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRegistroDePagos.setText("REGISTRO DE PAGOS");
        labelRegistroDePagos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelRegistroDePagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRegistroDePagosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelRegistroDePagosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelRegistroDePagosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelRegistroDePagosLayout = new javax.swing.GroupLayout(panelRegistroDePagos);
        panelRegistroDePagos.setLayout(panelRegistroDePagosLayout);
        panelRegistroDePagosLayout.setHorizontalGroup(
            panelRegistroDePagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelRegistroDePagos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelRegistroDePagosLayout.setVerticalGroup(
            panelRegistroDePagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelRegistroDePagos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        panelRound2.add(panelRegistroDePagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, 250, 70));

        panelModificarDatosUsuario.setBackground(new java.awt.Color(0, 0, 0));
        panelModificarDatosUsuario.setRoundBottomLeft(25);
        panelModificarDatosUsuario.setRoundBottomRight(25);
        panelModificarDatosUsuario.setRoundTopLeft(25);
        panelModificarDatosUsuario.setRoundTopRight(25);

        labelModificarDatosUsuario.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        labelModificarDatosUsuario.setForeground(new java.awt.Color(255, 255, 255));
        labelModificarDatosUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelModificarDatosUsuario.setText("MODIFICAR DATOS DE USUARIO");
        labelModificarDatosUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelModificarDatosUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelModificarDatosUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelModificarDatosUsuarioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelModificarDatosUsuarioLayout = new javax.swing.GroupLayout(panelModificarDatosUsuario);
        panelModificarDatosUsuario.setLayout(panelModificarDatosUsuarioLayout);
        panelModificarDatosUsuarioLayout.setHorizontalGroup(
            panelModificarDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelModificarDatosUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelModificarDatosUsuarioLayout.setVerticalGroup(
            panelModificarDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelModificarDatosUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );

        panelRound2.add(panelModificarDatosUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, -1));

        labelBienvenidos.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        labelBienvenidos.setText("!BIENVENIDO/A,");
        panelRound2.add(labelBienvenidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, -1, -1));

        imagenPuntosSuspensivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/Imagenes/puntosSuspensivos.png"))); // NOI18N
        panelRound2.add(imagenPuntosSuspensivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, -1, -1));

        labelNombreMostrar.setFont(new java.awt.Font("Roboto Black", 0, 48)); // NOI18N
        labelNombreMostrar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelNombreMostrar.setText("NombreApellido!");
        panelRound2.add(labelNombreMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 80, 470, -1));

        labelReloj.setFont(new java.awt.Font("Roboto Black", 0, 30)); // NOI18N
        labelReloj.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelReloj.setText("HORA: XX:XX:XX");
        panelRound2.add(labelReloj, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 340, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, 938, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 980, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void panelBotonExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBotonExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_panelBotonExitMouseClicked

    private void panelBotonExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBotonExitMouseEntered
        // TODO add your handling code here:
        panelBotonExit.setBackground(Color.red);
    }//GEN-LAST:event_panelBotonExitMouseEntered

    private void panelBotonExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBotonExitMouseExited
        // TODO add your handling code here:
        panelBotonExit.setBackground(new Color(243,243,243));
    }//GEN-LAST:event_panelBotonExitMouseExited

    private void labelVerEstacionamientoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelVerEstacionamientoMouseEntered
        
        labelVerEstacionamiento.setForeground(Color.orange);
        
    }//GEN-LAST:event_labelVerEstacionamientoMouseEntered

    private void labelVerEstacionamientoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelVerEstacionamientoMouseExited
        // TODO add your handling code here:
        labelVerEstacionamiento.setForeground(Color.white);
    }//GEN-LAST:event_labelVerEstacionamientoMouseExited

    private void labelRegistrarNuevoUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRegistrarNuevoUsuarioMouseEntered
        labelRegistrarNuevoUsuario.setForeground(Color.orange);
    }//GEN-LAST:event_labelRegistrarNuevoUsuarioMouseEntered

    private void labelRegistrarNuevoUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRegistrarNuevoUsuarioMouseExited
        labelRegistrarNuevoUsuario.setForeground(Color.white);
    }//GEN-LAST:event_labelRegistrarNuevoUsuarioMouseExited

    private void labelRegistrarPagoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRegistrarPagoMouseEntered
        labelRegistrarPago.setForeground(Color.orange);
    }//GEN-LAST:event_labelRegistrarPagoMouseEntered

    private void labelRegistrarPagoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRegistrarPagoMouseExited
        labelRegistrarPago.setForeground(Color.white);
    }//GEN-LAST:event_labelRegistrarPagoMouseExited

    private void labelModificarDatosUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelModificarDatosUsuarioMouseEntered
        labelModificarDatosUsuario.setForeground(Color.orange);
    }//GEN-LAST:event_labelModificarDatosUsuarioMouseEntered

    private void labelModificarDatosUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelModificarDatosUsuarioMouseExited
        labelModificarDatosUsuario.setForeground(Color.white);
    }//GEN-LAST:event_labelModificarDatosUsuarioMouseExited

    private void labelModificarTareasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelModificarTareasMouseEntered
        labelModificarTareas.setForeground(Color.orange);
    }//GEN-LAST:event_labelModificarTareasMouseEntered

    private void labelModificarTareasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelModificarTareasMouseExited
        labelModificarTareas.setForeground(Color.white);
    }//GEN-LAST:event_labelModificarTareasMouseExited

    private void labelModificarDisponibilidadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelModificarDisponibilidadMouseEntered
        labelModificarDisponibilidad.setForeground(Color.orange);
    }//GEN-LAST:event_labelModificarDisponibilidadMouseEntered

    private void labelModificarDisponibilidadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelModificarDisponibilidadMouseExited
        labelModificarDisponibilidad.setForeground(Color.white);
    }//GEN-LAST:event_labelModificarDisponibilidadMouseExited

    private void labelRegistroDePagosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRegistroDePagosMouseEntered
        labelRegistroDePagos.setForeground(Color.orange);
    }//GEN-LAST:event_labelRegistroDePagosMouseEntered

    private void labelRegistroDePagosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRegistroDePagosMouseExited
        labelRegistroDePagos.setForeground(Color.white);
    }//GEN-LAST:event_labelRegistroDePagosMouseExited

    private void labelModificarTareasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelModificarTareasMouseClicked
        ModificarTarifa ventana = new ModificarTarifa();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_labelModificarTareasMouseClicked

    private void labelRegistroDePagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRegistroDePagosMouseClicked

    }//GEN-LAST:event_labelRegistroDePagosMouseClicked

    private void labelVerEstacionamientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelVerEstacionamientoMouseClicked
        VerEstacionamiento ventana = new VerEstacionamiento();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_labelVerEstacionamientoMouseClicked

    private void labelRegistrarPagoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRegistrarPagoMouseClicked
        RegistrarPago ventana = new RegistrarPago();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_labelRegistrarPagoMouseClicked

    private void labelRegistrarNuevoUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRegistrarNuevoUsuarioMouseClicked
        //Vehiculo = usuario
        RegistrarVehiculo ventanaRegistrarVehiculo = new RegistrarVehiculo();
        ventanaRegistrarVehiculo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_labelRegistrarNuevoUsuarioMouseClicked
    
    //Funcion calcula del reloj
    private void calcula() {
        calendario = new GregorianCalendar();
        Date fechaHoraActual = new Date();

        calendario.setTime(fechaHoraActual);
        ampm = calendario.get(Calendar.AM_PM) == Calendar.AM ? "AM" : "PM";

        if (ampm.equals("PM")) {
            int h = calendario.get(Calendar.HOUR_OF_DAY) - 12;
            hora = h > 9 ? "" + h : "0" + h;
        } else {
            hora = calendario.get(Calendar.HOUR_OF_DAY) > 9 ? "" + calendario.get(Calendar.HOUR_OF_DAY)
                    : "0" + calendario.get(Calendar.HOUR_OF_DAY);
        }

        minutos = calendario.get(Calendar.MINUTE) > 9 ? "" + calendario.get(Calendar.MINUTE)
                : "0" + calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND) > 9 ? "" + calendario.get(Calendar.SECOND)
                : "0" + calendario.get(Calendar.SECOND);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new MenuAdministrador().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imagenPuntosSuspensivos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelBienvenidos;
    private javax.swing.JLabel labelExit;
    private javax.swing.JLabel labelModificarDatosUsuario;
    private javax.swing.JLabel labelModificarDisponibilidad;
    private javax.swing.JLabel labelModificarTareas;
    private javax.swing.JLabel labelNombreMostrar;
    private javax.swing.JLabel labelPark;
    private javax.swing.JLabel labelRegistrarNuevoUsuario;
    private javax.swing.JLabel labelRegistrarPago;
    private javax.swing.JLabel labelRegistroDePagos;
    private javax.swing.JLabel labelReloj;
    private javax.swing.JLabel labelSmart;
    private javax.swing.JLabel labelVerEstacionamiento;
    private javax.swing.JPanel panelBotonExit;
    private Interfaces.PanelRound panelGestionEspacios;
    private Interfaces.PanelRound panelModificarDatosUsuario;
    private Interfaces.PanelRound panelModificarDisponibilidad;
    private Interfaces.PanelRound panelModificarTareas;
    private Interfaces.PanelRound panelRegistrarNuevoUsuario;
    private Interfaces.PanelRound panelRegistroDePagos;
    private Interfaces.PanelRound panelRound2;
    private Interfaces.PanelRound panelVerEstacionamiento;
    // End of variables declaration//GEN-END:variables
    
    
    @Override
    public void run() {
        Thread currentThread = Thread.currentThread();

        while (currentThread == h1) {
            calcula(); // Actualiza el cálculo de la hora
            labelReloj.setText(hora + ":" + minutos + ":" + segundos + " " + ampm); // Actualiza el texto del label
            try {
                Thread.sleep(1000); // Pausa 1 segundo antes de actualizar nuevamente
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    }
}
